### PR TITLE
Nix service

### PR DESCRIPTION
**Pull request by angaz**
This configuration allows us to deploy the service on NixOS.

The `flake.nix` is getting a bit large. The standard is to add a `/nix` directory, and split out various parts of the configuration into separate files. I can do that now if we think it is a good idea. I didn't want to pollute the root of the project with yet another file. This shouldn't be something which is changed often, so I'm not so worried about a giant file.

I have this config deployed to my own NixOS server: https://node-crawler.s3fe.io/
I will keep this updated whenever I make changes for testing.

### CODE REVIEW

**Comment by angaz** [comment]
@taxmeifyoucan, You might find this interesting,

**Comment by angaz** [comment]
One bug I have realized with this setup: the discovery is configured to listen on a random port by default. So that means you have to either open basically all of the ephemeral ports on the firewall, or we could make flags for v4 and v5 ports separately, or we can do what geth does (but it's all private, so we would have to copy-paste the code) and have v4 send unhandled packets to v5: ethereum/go-ethereum/p2p/server.go:532, which would be quite a refactor on our side to have one discovery port. The latter being quite clean from the ops perspective, but I think two ports is a pretty OK way to go for something quick and easy.

**Comment by angaz** [comment]
I think a bad rebase automatically closed the PR. :joy:

**Comment by mohamedmansour** [comment]
@taxmeifyoucan can you please review this?

**Comment by mohamedmansour** [comment]
Is it ready to be merged? I like breaking out as you said in description, maybe can be done later!

**Comment by angaz** [comment]
> Is it ready to be merged? I like breaking out as you said in description, maybe can be done later!

Yeah it's good to go IMO. I've been using this setup on my server for a few weeks now. I see no issues. It's working great.

**Comment by mohamedmansour** [comment]
Awesome great work!

**Pull request merged**
